[tox]
minversion = 4.46.0
env_list = py{312}-ansible{218,220}
skip_missing_interpreters = true

[testenv]
deps = 
    -r tox-requirements.txt
    ansible220: ansible-core~=2.20.0
    ansible218: ansible-core~=2.18.0
commands =
    {posargs:molecule test -s tox --destroy always}